# Hugo
title = "Health Sutra"
description = "Rediscover the secret of healthy living with millet-rich breakfast and snack foods."
images = ["images/HS_Logo.png"]
custom_css = ["css/style.css"]

[social]
  instagram = "healthsutraofficial"
  twitter = "urhealthsutra"
  facebook = "healthsutraofficial"
